<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Clasificación de la Liga</title>\n";
echo "    <link rel=\"stylesheet\" href=\"styles.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "<header>\n";
echo "    <h1>Club Futbolero</h1>\n";
echo "    <nav>\n";
echo "        <ul>\n";
echo "            <li><a href=\"index.html\">Inicio</a></li>\n";
echo "            <li><a href=\"noticias.html\">Noticias</a></li>\n";
echo "            <li><a href=\"jugadores.html\">Jugadores</a></li>\n";
echo "            <li><a href=\"partidos.html\">Partidos</a></li>\n";
echo "            <li><a href=\"contacto.html\">Contacto</a></li>\n";
echo "            <li><a href=\"clasificacion.html\">clasificación</a></li>\n";
echo "        </ul>\n";
echo "    </nav>\n";
echo "</header>\n";
echo "<section class=\"section\">\n";
echo "    <h2>Clasificación de la Liga</h2>\n";
echo "    <table class=\"clasificacion-tabla\">\n";
echo "        <thead>\n";
echo "            <tr>\n";
echo "                <th>Clasificaion</th>\n";
echo "                <th>Equipo</th>\n";
echo "                <th>Pts</th>\n";
echo "                <th>Partidos Jugados</th>\n";
echo "                <th>Victorias</th>\n";
echo "                <th>Derrotas</th>\n";
echo "                <th>GF</th>\n";
echo "                <th>GC</th>\n";
echo "                <th>Clasificación</th>\n";
echo "            </tr>\n";
echo "        </thead>\n";
echo "        <tbody>\n";
echo "            <tr>\n";
echo "                <td>1</td>\n";
echo "                <td>Barcelona</td>\n";
echo "                <td>30</td>\n";
echo "                <td>11</td>\n";
echo "                <td>10</td>\n";
echo "                <td>1</td>\n";
echo "                <td>37</td>\n";
echo "                <td>10</td>\n";
echo "                <td class=\"champions\">Champions League</td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>2</td>\n";
echo "                <td>Real Madrid</td>\n";
echo "                <td>24</td>\n";
echo "                <td>11</td>\n";
echo "                <td>7</td>\n";
echo "                <td>1</td>\n";
echo "                <td>21</td>\n";
echo "                <td>11</td>\n";
echo "                <td class=\"champions\">Champions League</td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>3</td>\n";
echo "                <td>Villareal</td>\n";
echo "                <td>21</td>\n";
echo "                <td>11</td>\n";
echo "                <td>6</td>\n";
echo "                <td>2</td>\n";
echo "                <td>20</td>\n";
echo "                <td>19</td>\n";
echo "                <td class=\"champions\">Champions League</td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>4</td>\n";
echo "                <td>Atletico de Madrid</td>\n";
echo "                <td>20</td>\n";
echo "                <td>11</td>\n";
echo "                <td>5</td>\n";
echo "                <td>1</td>\n";
echo "                <td>16</td>\n";
echo "                <td>7</td>\n";
echo "                <td class=\"champions\">Champions League</td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>5</td>\n";
echo "                <td>Athletic</td>\n";
echo "                <td>18</td>\n";
echo "                <td>11</td>\n";
echo "                <td>5</td>\n";
echo "                <td>3</td>\n";
echo "                <td>17</td>\n";
echo "                <td>11</td>\n";
echo "                <td class=\"europa league\">Europa Legue</td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>6</td>\n";
echo "                <td>Betis</td>\n";
echo "                <td>18</td>\n";
echo "                <td>11</td>\n";
echo "                <td>5</td>\n";
echo "                <td>3</td>\n";
echo "                <td>11</td>\n";
echo "                <td>9</td>\n";
echo "                <td class=\"liga conferencia\">Liga Conferencia</td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>18</td>\n";
echo "                <td>Las Palmas</td>\n";
echo "                <td>9</td>\n";
echo "                <td>11</td>\n";
echo "                <td>2</td>\n";
echo "                <td>6</td>\n";
echo "                <td>13</td>\n";
echo "                <td>19</td>\n";
echo "                <td class=\"descenso\">Descenso</td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>19</td>\n";
echo "                <td>Valladolid</td>\n";
echo "                <td>8</td>\n";
echo "                <td>11</td>\n";
echo "                <td>2</td>\n";
echo "                <td>7</td>\n";
echo "                <td>9</td>\n";
echo "                <td>23</td>\n";
echo "                <td class=\"descenso\">Descenso</td>\n";
echo "            </tr>\n";
echo "            <tr>\n";
echo "                <td>20</td>\n";
echo "                <td>Valencia C.F.</td>\n";
echo "                <td>7</td>\n";
echo "                <td>11</td>\n";
echo "                <td>1</td>\n";
echo "                <td>6</td>\n";
echo "                <td>8</td>\n";
echo "                <td>17</td>\n";
echo "                <td class=\"descenso\">Descenso</td>\n";
echo "            </tr>\n";
echo "        </tr>\n";
echo "    </tr>\n";
echo "        </tbody>\n";
echo "    </table>\n";
echo "</section>\n";
echo "<footer>\n";
echo "    <p>© 2024 Club Futbolero. Todos los derechos reservados.</p>\n";
echo "</footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
?>