<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Contacto - Club Futbolero</title>\n";
echo "    <link rel=\"stylesheet\" href=\"styles.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    <header>\n";
echo "        <h1>Club Futbolero</h1>\n";
echo "        <nav>\n";
echo "            <ul>\n";
echo "                <li><a href=\"inicio.html\">Inicio</a></li>\n";
echo "                <li><a href=\"noticias.html\">Noticias</a></li>\n";
echo "                <li><a href=\"jugadores.html\">Jugadores</a></li>\n";
echo "                <li><a href=\"partidos.html\">Partidos</a></li>\n";
echo "                <li><a href=\"contacto.html\">Contacto</a></li>\n";
echo "                <li><a href=\"clasificacion.html\">clasificacion</a></li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "                \n";
echo "    <div class=\"contact-container\">\n";
echo "        <h1>Contáctanos</h1>\n";
echo "        <form id=\"contact-form\">\n";
echo "            <label for=\"name\">Nombre:</label>\n";
echo "            <input type=\"text\" id=\"name\" name=\"name\" required>\n";
echo "            <label for=\"email\">Correo Electrónico:</label>\n";
echo "            <input type=\"email\" id=\"email\" name=\"email\" required>\n";
echo "            <label for=\"message\">Mensaje:</label>\n";
echo "            <textarea id=\"message\" name=\"message\" rows=\"4\" required></textarea>\n";
echo "            <button type=\"submit\">Enviar</button>\n";
echo "        </form>\n";
echo "    </div>\n";
echo "    <footer>\n";
echo "        <p>&copy; 2024 Club Futbolero. Todos los derechos reservados.</p>\n";
echo "    </footer>\n";
echo "</body>   \n";
echo "<!DOCTYPE html>\n";
echo "\n";
?>