<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Inicio - Club Futbolero </title>\n";
echo "    <link rel=\"stylesheet\" href=\"styles.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    <header>\n";
echo "        <h1>Club Futbolero</h1>\n";
echo "        <nav>\n";
echo "            <ul>\n";
echo "                <li><a href=\"inicio.html\">Inicio</a></li>\n";
echo "                <li><a href=\"noticias.html\">Noticias</a></li>\n";
echo "                <li><a href=\"jugadores.html\">Jugadores</a></li>\n";
echo "                <li><a href=\"partidos.html\">Partidos</a></li>\n";
echo "                <li><a href=\"contacto.html\">Contacto</a></li>\n";
echo "                <li><a href=\"clasificacion.html\">clasificacion</a></li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "    <section class=\"section\">\n";
echo "        <h2>Bienvenidos a Club Futbolero</h2>        \n";
echo "        <p>¡Bienvenidos al sitio oficial de Fútbol Club, el hogar de los apasionados del fútbol! Aquí, los aficionados podrán encontrar toda la información relevante sobre sus equipo y el emocionante mundo del deporte más popular del planeta. Desde las noticias más frescas hasta la información completa sobre nuestros jugadores, partidos y eventos, esta página es tu lugar de referencia para estar al tanto de todo lo que ocurre en el club.\n";
echo "            En Club Futbolero, valoramos el espíritu de equipo, la dedicación y el esfuerzo en el campo. Nuestra misión es conectar a los fans con el corazón y la historia del equipo, proporcionando una experiencia digital completa que permita acceder de manera sencilla y rápida a todas las novedades. Explora nuestro calendario de partidos, conoce a los jugadores, revisa las últimas noticias y, por supuesto, no dudes en comunicarte con nosotros para hacer de esta comunidad un lugar aún mejor.\n";
echo "            Gracias por formar parte de Club Futbolero, donde cada partido es una historia, cada gol es una victoria y cada aficionado es parte de nuestra gran familia. ¡Acompáñanos en esta aventura futbolística!\n";
echo "            </p>\n";
echo "        <p><b>Actualización semanal de estadísticas:</b> consulta los logros y el rendimiento de cada equipo en cada jornada y diviertete con Club Futbolero.</p>\n";
echo "        <img src=\"atleti.jpg\" alt=\"Imagen del equipo de fútbol\" class=\"hero-img\">\n";
echo "    </section>\n";
echo "    <footer>\n";
echo "        <p>&copy; 2024 Club Futbolero. Todos los derechos reservados.</p>\n";
echo "    </footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
?>