<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Jugadores - Club Futbolero</title>\n";
echo "    <link rel=\"stylesheet\" href=\"styles.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    <header>\n";
echo "        <h1>Club Futbolero</h1>\n";
echo "        <nav>\n";
echo "            <ul>\n";
echo "                <li><a href=\"inicio.html\">Inicio</a></li>\n";
echo "                <li><a href=\"noticias.html\">Noticias</a></li>\n";
echo "                <li><a href=\"jugadores.html\">Jugadores</a></li>\n";
echo "                <li><a href=\"partidos.html\">Partidos</a></li>\n";
echo "                <li><a href=\"contacto.html\">Contacto</a></li>\n";
echo "                <li><a href=\"clasificacion.html\">clasificacion</a></li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "    <section class=\"section\">\n";
echo "        <h2>Jugadores más destacados de la liga</h2>\n";
echo "        <div class=\"jugador\">\n";
echo "            <h3>Robert Lewandowski</h3>\n";
echo "            <p>Posición: Delantero</p>\n";
echo "            <p>Número: 9</p>\n";
echo "            <p>Goles: 15</p>\n";
echo "            <p>Asistencias: 2</p>\n";
echo "        </div>\n";
echo "        <div class=\"jugador\">\n";
echo "            <h3>Kylian Mbappé</h3>\n";
echo "            <p>Posición: Delantero</p>\n";
echo "            <p>Número: 9</p>\n";
echo "            <p>Asistencias: 1</p>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "    <footer>\n";
echo "        <p>&copy; 2024 Fútbol Club. Todos los derechos reservados.</p>\n";
echo "    </footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
?>