<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Noticias - Club Futbolero</title>\n";
echo "    <link rel=\"stylesheet\" href=\"styles.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    <header>\n";
echo "        <h1>Club Futbolero</h1>\n";
echo "        <nav>\n";
echo "            <ul>\n";
echo "                <li><a href=\"inicio.html\">Inicio</a></li>\n";
echo "                <li><a href=\"noticias.html\">Noticias</a></li>\n";
echo "                <li><a href=\"jugadores.html\">Jugadores</a></li>\n";
echo "                <li><a href=\"partidos.html\">Partidos</a></li>\n";
echo "                <li><a href=\"contacto.html\">Contacto</a></li>\n";
echo "                <li><a href=\"clasificacion.html\">clasificacion</a></li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "    <section class=\"section\">\n";
echo "        <h2>Últimas Noticias</h2>\n";
echo "        <article>\n";
echo "            <h3>¡Victoria arrolladora en el último partido!</h3>\n";
echo "            <p>El Fútbol Club Barcelona  ha ganado el partido con un arrollador 4-0 contra el poderoso Real Madrid. Detalles y análisis del partido aquí.</p>\n";
echo "        </article>\n";
echo "        <article>\n";
echo "            <h3>Nuevo fichaje para la plantilla rojiblaca: Pep Guardiola ya esta entrenado a los jugadores del Atletico de Madrid</h3>\n";
echo "            <p>El entrenador español se une al conjunto colchonero. Conoce su trayectoria y lo que puede aportar a nuestro club.</p>\n";
echo "        </article>\n";
echo "        <article>\n";
echo "            <h3>Noticia de ultimo momento: Ficticius se lamenta en casa por la perdida del ansiado balon de oro</h3>\n";
echo "            <p>El jugador brasileño pierde el trofeo con un segundo puesto a manos del centrocampista español Rodri Hernández.</p>\n";
echo "        </article>\n";
echo "    </section>\n";
echo "    <footer>\n";
echo "        <p>&copy; 2024 Fútbol Club. Todos los derechos reservados.</p>\n";
echo "    </footer>\n";
echo "</body>\n";
echo "</html>\n";
?>