<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Partidos - Club Futbolero</title>\n";
echo "    <link rel=\"stylesheet\" href=\"styles.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    <header>\n";
echo "        <h1>Club Futbolero</h1>\n";
echo "        <nav>\n";
echo "            <ul>\n";
echo "                <li><a href=\"inicio.html\">Inicio</a></li>\n";
echo "                <li><a href=\"noticias.html\">Noticias</a></li>\n";
echo "                <li><a href=\"jugadores.html\">Jugadores</a></li>\n";
echo "                <li><a href=\"partidos.html\">Partidos</a></li>\n";
echo "                <li><a href=\"contacto.html\">Contacto</a></li>\n";
echo "                <li><a href=\"clasificacion.html\">clasificacion</a></li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "    <section class=\"section\">\n";
echo "        <h2>Calendario de Partidos de la Jornada 12</h2>\n";
echo "        <p>Alavés vs R.C.D Mallorca - 1-0</p>\n";
echo "        <p>Girona vs Leganés - Emitiendo</p>\n";
echo "        <p>Valencia C.F vs Real Madrid - Cancelado</p>\n";
echo "        <p>Barcelona vs RCD Español - 2-0</p>\n";
echo "        <p>Athletic vs Betis - 3-1</p>\n";
echo "        <p>Osasuna vs Valladolid - 1-0</p>\n";
echo "        <p>Villarreal vs Rayo Vallecano - Por jugar</p>\n";
echo "        <p>Atlético de Madrid vs U.D. Las Palmas - 4-0</p>\n";
echo "        <p>Sevilla vs Real Sociedad - Por jugar</p>\n";
echo "        <p>Celta de Vigo vs Getafe - 1-2</p>\n";
echo "    </section>\n";
echo "    <footer>\n";
echo "        <p>&copy; 2024 Club Futbolero. Todos los derechos reservados.</p>\n";
echo "    </footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
?>